package com.sportzinteractive.baseprojectsetup.business.domain.model.footballstandings

import com.sportzinteractive.baseprojectsetup.business.domain.model.footballfixtures.Matches

data class Team(
    val teamId: Int?,
    val teamGlobalId: Int?,
    val teamName: String?,
    val match: List<Match>? = null,
    val teamShortName: String?,
    val teamDisplayName: String?,
    val position: String?,
    val prevPosition: String?,
    val positionStatus: String?,
    val played: String?,
    val wins: String?,
    val lost: String?,
    val tied: String?,
    val draws: String?,
    val noResult: String?,
    val scoreDiff: String?,
    val pointsConceded: String?,
    val pointsScored: String?,
    val points: String?,
    val carryForwardPoints: String?,
    val totalPoints: String?,
    val awayWins: String?,
    val awayPointsConceded: String?,
    val awayPointsScored: String?,
    val homeWins: String?,
    val isQualified: Boolean?,
    val ga: String?,
    val gf: String?,
    val pointsPerMatch: Int?,
    val overallPointsPerMatch: Int?,
    val trumpMatchesWon: String?,
    val teamLogo: String?,
    var upcomingMatchItem: Matches? = null,
)
